"""§5.2 correction: verify which Jacobian the null-space projector P_N was
actually built from, vs which Jacobian the command u was actually solved
with.

An external reviewer flagged a mathematical inconsistency: for damped least
squares, u = J^T(JJ^T+lambda^2 I)^-1 e, u lies EXACTLY in row(J) for any
damping value (u = J^T @ anything is always a linear combination of J's
rows). So if P_N = I - J^+ J is built from the SAME J the command was
solved with, P_N @ u must be ~0 to floating-point precision, regardless of
conditioning. The original h3b_workspace_and_nullspace.py /
h3b_pipeline_stage_nullspace.py / lag_chronology_analysis.py all built P_N
from live_jac.live_jacobian(state, contact=...) -- the contact model
RECOMPUTED AT THE MEASURED STATE -- while the actual command u = out["u0"]
was solved by the real controller using the SCHEDULED Jacobian at that
tick's reference index (confirmed directly from
inverse_jacobian_controller.py's solve(): `jacobian = self._schedule[index]`).
These are different matrices whenever the schedule and the live model
disagree, so E_N as originally computed could never have measured "null-
space motion generated by the control law's own solve" (identically zero
by construction) -- it measures schedule-vs-state Jacobian mismatch,
channelled through the executed command's own direction.

This script reproduces the check directly: at a few sample ticks of one
selective no-contact run, compute E_N twice -- once with P_N built from the
SAME schedule Jacobian the command used (should be ~0), once with P_N built
from live_jac's state-recomputed Jacobian (reproduces the original,
non-zero values) -- confirming both the mathematical claim and which
matrix the original analysis actually used.

Read-only; writes nothing (verification only, run directly and read off
stdout; see STAGE3_FINAL_REPORT_REVISED.md §5.2 for the numbers quoted
from this script's output).
"""
import sys
sys.path.insert(0, "/home/jack/.claude/jobs/ea647104/tmp/stage3_prior")
import numpy as np
import manifest
import loader
import live_jac

SCHED_NC = f"{loader.REPO}/plans/stage3_design/mpc_schedules/vessel_nc_schedule_phi30_L30_newwall_2026-10-06.npy"
sched = np.load(SCHED_NC)

rm = next(r for r in manifest.RUNS if r["dirname"] == "vessel_invjac_clip_nocontact_floor255_20261008T151002Z")
out, meta = loader.enrich_run(rm)
q = out["q_meas_rad"]
L = out["insertion_length_m"]
u = out["u0"]


def null_space_energy(J, uu):
    J_pinv = np.linalg.pinv(J)
    P_N = np.eye(7) - J_pinv @ J
    u_N = P_N @ uu
    return float(u_N @ u_N / max(uu @ uu, 1e-18))


print(f"{'tick':>5} {'E_N (P_N from J_sched -- SAME J the solve used)':>48} "
      f"{'E_N (P_N from J_live -- DIFFERENT J)':>38} {'||J_live-J_sched||/||J_sched||':>30}")
for k in (50, 250, 350):
    ref_idx = int(np.clip(out["ref_index"][k] + 1, 0, sched.shape[0] - 1))
    J_sched = sched[ref_idx]
    state7 = np.concatenate([q[k], [L[k]]])
    J_live = live_jac.live_jacobian(state7, contact=False)
    uk = u[k]

    en_same_J = null_space_energy(J_sched, uk)
    en_different_J = null_space_energy(J_live, uk)
    rel_mismatch = float(np.linalg.norm(J_live - J_sched) / np.linalg.norm(J_sched))

    print(f"{k:>5} {en_same_J:>48.3e} {en_different_J:>38.4f} {rel_mismatch:>30.3f}")

print("\nConclusion: E_N computed with P_N from the Jacobian the command was "
      "actually solved with (J_sched) is ~0 to floating-point precision at "
      "every tick, exactly as the mathematics of damped least squares "
      "requires. E_N computed with P_N from a DIFFERENT Jacobian (J_live, "
      "the state-recomputed contact model) -- what the original analysis "
      "actually did -- is substantial, and tracks the schedule-vs-live "
      "relative mismatch. This confirms E_N, as reported in the earlier "
      "version of §5.2, measures schedule-vs-state Jacobian mismatch, not "
      "the control law's own null-space behaviour.")
